# This is a basic workflow to help you get started with Actions

name: Monthly update Rotweer

# Controls when the workflow will run
on:
  schedule:
    -  cron: '0 7 3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rotweer:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies
        run: |
          sudo apt install libcurl4-openssl-dev
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master

      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("janitor")'
          R -e 'install.packages("slider")'
          R -e 'install.packages("showtext")'
          R -e 'install.packages("patchwork")'
      - name: Rotweer
        run: Rscript R/rotweer.R

      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add plots/*
          git commit -am "GH ACTION Autorun ${date}"
          git push
        env:
          REPO_KEY: ${{secrets.GITHUB-TOKEN}}
          username: github-actions
